name: CI

on:
    push:
        branches:
            - main    
    pull_request:
        branches:
            - main

jobs:
    # build:
        # runs-on: ubuntu-latest

        # steps:
        # - name: Checkout code
        #     uses: actions/checkout@v2

        # - name: Set up Node.js
        #     uses: actions/setup-node@v2
        #     with:
        #     node-version: '14'

        # - name: Install dependencies
        #     run: npm install

        # - name: Run tests
        #     run: npm test
    
    test:
        name: Run Tests
        timeout-minutes: 15 # Set a timeout for the test job
        runs-on: self-hosted # Use self-hosted runners for testing

        strategy:
            matrix:
                node-version: [22] # Test on multiple Node.js versions

        environment: MONGO_URI

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        #- run: pm2 stop all

        - name: Install Backend Dependencies
          working-directory: ./backend
          run: | 
                npm install --global yarn
                yarn --version
                yarn install
        
        - name: Install Frontend Dependencies
          working-directory: ./frontend
          run: | 
            df -h
            sudo rm -rf ./build
            yarn install
            yarn run build

        - run: npm ci
        - run: | 
            cd ./backend
            touch .env
            echo "${{ secrets.PROD }}" > .env
    
    
            # Run backend tests
        - name: Run Backend Tests
          env:
           MONGO_URI: ${{ secrets.MONGO_URI }}
           JWT_SECRET: ${{ secrets.JWT_SECRET }}
           PORT: ${{ secrets.PORT }}
           working-directory: ./backend
          run: npm test

        - run: pm2 start all

        - run: pm2 restart all


